"""Regenerate `app/render/countries.py` from the live corpus. Development only.

The choropleth needs ISO-3166 alpha-3 codes, and ClinicalTrials.gov publishes country **names**
whose spellings are its own: "South Korea" rather than "Korea, Republic of", "Turkey (Türkiye)"
rather than "Türkiye". A hand-maintained map drifts against those spellings silently — one
unmatched name used to collapse an entire choropleth into a table.

So the map is generated from two authoritative sources and committed:

- the names come from `/stats/field/values?fields=LocationCountry`, which returns the
  **corpus-wide** distinct values (226 of them) — one of the few things that endpoint is good
  for, since it refuses any filter (notes §1);
- the codes come from `pycountry`, a packaged copy of the ISO-3166 tables.

`pycountry` is deliberately **not** a runtime dependency: it is used here, once, and its output
is checked in. Run with `uv run --with pycountry python scripts/build_country_map.py`.
"""

from __future__ import annotations

import json
import urllib.request
from pathlib import Path
from typing import Any

STATS_URL = (
    "https://clinicaltrials.gov/api/v2/stats/field/values?fields=LocationCountry&types=STRING"
)
TARGET = Path(__file__).resolve().parent.parent / "app" / "render" / "countries.py"

# Names ClinicalTrials.gov uses that ISO-3166's own spelling does not match. Each is a real
# value observed in the corpus, not a guess.
ALIASES: dict[str, str] = {
    "South Korea": "KOR",
    "North Korea": "PRK",
    "Turkey (Türkiye)": "TUR",
    "Türkiye": "TUR",
    "Russia": "RUS",
    "Iran": "IRN",
    "Syria": "SYR",
    "Vietnam": "VNM",
    "Laos": "LAO",
    "Taiwan": "TWN",
    "Macedonia": "MKD",
    "North Macedonia": "MKD",
    "Moldova": "MDA",
    "Tanzania": "TZA",
    "Bolivia": "BOL",
    "Venezuela": "VEN",
    "Brunei Darussalam": "BRN",
    "Brunei": "BRN",
    "Cape Verde": "CPV",
    "Ivory Coast": "CIV",
    "Democratic Republic of the Congo": "COD",
    "The Democratic Republic of the Congo": "COD",
    "Congo": "COG",
    "Palestinian Territories": "PSE",
    "Palestinian Territory, occupied": "PSE",
    "Former Serbia and Montenegro": "SCG",
    "Former Yugoslavia": "YUG",
    "Netherlands Antilles": "ANT",
    "Serbia and Montenegro": "SCG",
    "Swaziland": "SWZ",
    "Eswatini": "SWZ",
    "Czech Republic": "CZE",
    "Czechia": "CZE",
    "Burma": "MMR",
    "Myanmar": "MMR",
    "East Timor": "TLS",
    "Timor-Leste": "TLS",
    "Vatican City State": "VAT",
    "Holy See (Vatican City State)": "VAT",
    "Saint Barthelemy": "BLM",
    "Saint Martin": "MAF",
    "Sint Maarten": "SXM",
    "Curacao": "CUW",
    "Réunion": "REU",
    "Reunion": "REU",
    # The remaining twelve the ISO tables do not match by name. Note the trailing space on
    # Bonaire: it is in the upstream value itself, and stripping it here would mean the key never
    # matches what the API returns.
    "Côte d\u2019Ivoire": "CIV",
    "The Gambia": "GMB",
    "The Bahamas": "BHS",
    "Macau": "MAC",
    "Virgin Islands": "VIR",
    "Holy See": "VAT",
    "Aland Islands": "ALA",
    "Micronesia": "FSM",
    "French Southern and Antarctic Lands": "ATF",
    "Bonaire, Saint Eustatius and Saba ": "BES",
    # No ISO-3166 code of its own; XKX is the widely used user-assigned stand-in.
    "Kosovo": "XKX",
    # A state that no longer exists. Kept so historical records place rather than vanish.
    "Federal Republic of Yugoslavia": "YUG",
}


def fetch_country_names() -> list[str]:
    with urllib.request.urlopen(STATS_URL, timeout=30) as response:
        payload: Any = json.loads(response.read())
    node = payload[0] if isinstance(payload, list) else payload
    values = node.get("topValues") or node.get("values") or []
    return [str(entry["value"]) for entry in values if entry.get("value")]


def resolve(name: str) -> str | None:
    import pycountry

    if name in ALIASES:
        return ALIASES[name]
    try:
        match = pycountry.countries.lookup(name)
    except LookupError:
        return None
    return str(match.alpha_3)


def main() -> int:
    names = fetch_country_names()
    resolved: dict[str, str] = {}
    unmatched: list[str] = []

    for name in names:
        code = resolve(name)
        if code is None:
            unmatched.append(name)
        else:
            resolved[name] = code

    lines = [
        '"""ISO-3166 alpha-3 codes for the country names ClinicalTrials.gov actually returns.',
        "",
        "GENERATED by `scripts/build_country_map.py` — edit that, not this.",
        "",
        f"Covers {len(resolved)} of the {len(names)} distinct `LocationCountry` values in the",
        "corpus. Anything unmatched is listed in `UNMAPPED` rather than dropped silently, so a",
        "choropleth can name what it could not place.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from typing import Final",
        "",
        "ISO_A3: Final[dict[str, str]] = {",
    ]
    lines += [f'    "{name}": "{code}",' for name, code in sorted(resolved.items())]
    lines += [
        "}",
        "",
        "UNMAPPED: Final[tuple[str, ...]] = (",
        *[f'    "{name}",' for name in sorted(unmatched)],
        ")",
        '"""Corpus values with no ISO-3166 country code — historical states and groupings."""',
        "",
    ]

    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(Path.cwd())}: {len(resolved)} mapped, {len(unmatched)} not")
    for name in unmatched:
        print("  unmapped:", name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
